tap 'buo/cask-upgrade'
tap 'homebrew/services'
tap 'homebrew/cask-versions'
tap 'universal-ctags/universal-ctags'
cask 'osxfuse'
brew 'ansible'
brew 'apr-util'
brew 'awscli'
brew 'bash'
brew 'brew-gem'
brew 'colordiff'
brew 'coreutils'
brew 'curl', args: ['with-c-ares', 'with-gssapi', 'with-libidn', 'with-nghttp2']
brew 'git'
brew 'gnu-sed'
brew 'gnu-tar'
brew 'gnupg'
brew 'go'
brew 'grc'
brew 'grep', args: ['with-default-names']
brew 'htop'
brew 'jmeter'
brew 'jq'
brew 'lesspipe', args: ['with-syntax-highlighting']
brew 'mas'
brew 'media-info'
brew 'midnight-commander'
brew 'mitmproxy'
brew 'moreutils'
brew 'mpv'
brew 'mtr'
brew 'nmap'
brew 'p7zip'
brew 'packer'
brew 'pbzip2'
brew 'perl'
brew 'pigz'
brew 'pv'
brew 'python'
brew 'python@2'
brew 'ranger'
brew 'ruby'
brew 'shellcheck'
brew 'sqlite'
brew 'ssh-copy-id'
brew 'sshfs'
brew 'terraform'
brew 'the_silver_searcher'
brew 'tig'
brew 'tmux'
brew 'tree'
brew 'universal-ctags/universal-ctags/universal-ctags', args: ['HEAD']
brew 'unrar'
brew 'vim', args: ['with-luajit', 'with-python3', 'with-override-system-vi']
brew 'watch'
brew 'wget'
brew 'zsh'
cask 'alfred'
cask 'bartender'
cask 'bettertouchtool'
cask 'bitwarden'
cask 'cakebrew'
cask 'google-chrome'
cask 'dash'
cask 'dbeaver-community'
cask 'docker'
cask 'firefox'
cask 'firefox-developer-edition'
cask 'marshallofsound-google-play-music-player'
cask 'iterm2'
cask 'java'
cask 'karabiner-elements'
cask 'pocket-casts'
cask 'steam'
cask 'sublime-text'
cask 'sublime-merge'
cask 'telegram-desktop'
cask 'vagrant'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
mas 'Tweetbot', id: 557168941
mas 'The Unarchiver', id: 425424353
mas 'Reeder', id: 880001334
