set nocompatible

" set default 'runtimepath' (without ~/.vim folders)
let &runtimepath = printf('%s/vimfiles,%s,%s/vimfiles/after', $VIM, $VIMRUNTIME, $VIM)
" what is the name of the directory containing this file?
let s:portable = expand('<sfile>:p:h')
" add the directory to 'runtimepath'
let &runtimepath = printf('%s,%s,%s/after', s:portable, &runtimepath, s:portable)

call pathogen#infect()
call pathogen#helptags()

set viminfo='1000,n~/.dotfiles/vim/.viminfo

let g:backup_directory=$HOME . '/.local/share/backups'

set background=dark
let g:solarized_termtrans=1
let g:solarized_termcolors=256
let g:solarized_underline=0
set t_Co=256
colorscheme solarized

set filetype=on
set shiftround
set showmatch " show matching brackets when text indicator is over them
set incsearch " do incremental searching
set hlsearch " highlight search results
set ignorecase " ignore case when searching
set smartcase " when searching try to be smart about cases
set nowrap
set ttyfast
set lazyredraw
set clipboard=unnamed,unnamedplus
set list listchars=tab:>-,trail:·,extends:>,precedes:<
set mouse=a
set showmode
set number
set cursorline

" scrolling
set scrolloff=8 "start scrolling when we're 8 lines away from margins
set sidescrolloff=15
set sidescroll=1

" hotkeys
set pastetoggle=<F2>
nnoremap <F2> :set invpaste paste?<CR>
nnoremap <F3> :NumbersToggle<CR>
inoremap <F3> <ESC>:NumbersToggle<CR>
nnoremap <F4> :Dash<CR>
inoremap <F4> <ESC>:Dash<CR>
nnoremap <F5> :Ag<CR>
inoremap <F5> <ESC>:Ag<CR>
nnoremap <F6> :NERDTreeToggle<CR>
inoremap <F6> <ESC>:NERDTreeToggle<CR>

" I prefer to use arrows
" Alt left/right to switch buffers. Terminal should be configured to send escape sequences for them.
nnoremap <ESC>b :bprev<CR>
inoremap <ESC>b <ESC>:bprev<CR>
nnoremap <ESC>f :bnext<CR>
inoremap <ESC>f <ESC>:bnext<CR>
" Ctrl arrows to switch between splits and tmux panes
let g:tmux_navigator_no_mappings = 1
nnoremap <silent> <C-Left> :TmuxNavigateLeft<cr>
nnoremap <silent> <C-Down> :TmuxNavigateDown<cr>
nnoremap <silent> <C-Up> :TmuxNavigateUp<cr>
nnoremap <silent> <C-Right> :TmuxNavigateRight<cr>
nnoremap <silent> <C-\> :TmuxNavigatePrevious<cr>

" Change cursor shape in different modes
if exists('$TMUX')
    let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
    let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
else
    let &t_SI = "\<Esc>]50;CursorShape=1\x7"
    let &t_EI = "\<Esc>]50;CursorShape=0\x7"
endif

" enable proper space and cr expansion inside brackets
let delimitMate_expand_cr=1
let delimitMate_expand_space=1

" don't conceal quotes in json
let g:vim_json_syntax_conceal=0

" Enable airline tabline
let g:airline#extensions#tabline#enabled=1

" NERDTree auto start
autocmd VimEnter * if &filetype !=# 'gitcommit' && &filetype !=# 'crontab' | NERDTree | endif
" Go to previous (last accessed) window if started with some arguments
autocmd VimEnter * if argc() | wincmd p | endif
autocmd BufEnter * if winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree() | q | endif

" markdown tunings
let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_frontmatter = 1
let g:vim_markdown_json_frontmatter = 1

" Allow saving of files as sudo when I forgot to start vim using sudo
cmap w!! %!sudo tee > /dev/null %

" handle crontab files properly
autocmd filetype crontab setlocal nobackup nowritebackup
