set nocompatible

" Set default 'runtimepath' without ~/.vim folders
let &runtimepath=printf('%s/vimfiles,%s,%s/vimfiles/after', $VIM, $VIMRUNTIME, $VIM)
" What is the name of the directory containing this file?
let s:portable=expand('<sfile>:p:h')
" Add the directory to 'runtimepath'
let &runtimepath=printf('%s,%s,%s/after', s:portable, &runtimepath, s:portable)

call pathogen#infect()
call pathogen#helptags()

set viminfo='1000,n$XDG_CACHE_HOME/vim/info

let g:backup_directory=$XDG_DATA_HOME . '/.local/share/backups'

set background=dark
let g:solarized_termtrans=1
let g:solarized_termcolors=256
let g:solarized_underline=0
set t_Co=256
colorscheme solarized

set filetype=on
set shiftround
set showmatch " show matching brackets when text indicator is over them
set incsearch " do incremental searching
set hlsearch " highlight search results
set ignorecase " ignore case when searching
set smartcase " when searching try to be smart about cases
set nowrap
set ttyfast
set lazyredraw
set clipboard=unnamed,unnamedplus
set list listchars=tab:>-,trail:·,extends:>,precedes:<
set mouse=a
set showmode
set number
set cursorline

" Scrolling
set scrolloff=8 "start scrolling when we're 8 lines away from margins
set sidescrolloff=15
set sidescroll=1

" Folding
set foldmethod=indent
set foldnestmax=10
set nofoldenable
set foldlevel=2
let g:SimpylFold_docstring_preview=1

" Use Space to toggle folding
nnoremap <Space> za
vnoremap <Space> zf

" Fn hotkeys
set pastetoggle=<F2>
nnoremap <F2> :set invpaste paste?<CR>
nnoremap <F3> :NumbersToggle<CR>
inoremap <F3> <ESC>:NumbersToggle<CR>
nnoremap <F4> :Dash<CR>
inoremap <F4> <ESC>:Dash<CR>
nnoremap <F5> :Ag<CR>
inoremap <F5> <ESC>:Ag<CR>
nnoremap <F6> :NERDTreeTabsToggle<CR>
inoremap <F6> <ESC>:NERDTreeTabsToggle<CR>
nnoremap <F7> :TagbarToggle<CR>
inoremap <F7> <ESC>:TagbarToggle<CR>

" Alt left/right to switch buffers. Terminal should be configured to send porper escape sequences
nnoremap <ESC>b :bprev<CR>
inoremap <ESC>b <ESC>:bprev<CR>
nnoremap <ESC>f :bnext<CR>
inoremap <ESC>f <ESC>:bnext<CR>

" Ctrl arrows to switch between splits and tmux panes
let g:tmux_navigator_no_mappings=1
nnoremap <silent> <C-Left> :TmuxNavigateLeft<cr>
nnoremap <silent> <C-Down> :TmuxNavigateDown<cr>
nnoremap <silent> <C-Up> :TmuxNavigateUp<cr>
nnoremap <silent> <C-Right> :TmuxNavigateRight<cr>
nnoremap <silent> <C-\> :TmuxNavigatePrevious<cr>

" Change cursor shape in different modes
if exists('$TMUX')
    let &t_SI="\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
    let &t_EI="\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
else
    let &t_SI="\<Esc>]50;CursorShape=1\x7"
    let &t_EI="\<Esc>]50;CursorShape=0\x7"
endif

" Enable proper space and cr expansion inside brackets
let delimitMate_expand_cr=1
let delimitMate_expand_space=1

" Don't conceal quotes in JSON
let g:vim_json_syntax_conceal=0

" Enable airline tabline
let g:airline#extensions#tabline#enabled=1

" Automatic tags creation tuning
let g:easytags_async=1
let g:easytags_file=$XDG_CACHE_HOME . '/vim/tags'

" Markdown tuning
let g:vim_markdown_frontmatter=1
let g:vim_markdown_json_frontmatter=1

" Allow saving of files as sudo when I forgot to start vim using sudo
cmap w!! %!sudo tee > /dev/null %

" Handle crontab files properly
autocmd filetype crontab setlocal nobackup nowritebackup
