vim.loader.enable()

require('options')
require('colorscheme')
require('keymaps')
require('whichkey')
require('treesitter')
require('plugins')
require('committia')
require('tree')
require('statusbar')
require('lsp')
require('fuzzy')
