vim.loader.enable()

require('options')
pcall(require, 'local_options') -- attempt to load local_options.lua, ignore missing
require('colorscheme')
require('keymaps')
require('whichkey')
require('treesitter')
require('plugins')
require('committia')
require('tree')
require('statusbar')
require('lsp')
require('fuzzy')
require('numbertoggle')
