# Get absolute path for zshdir and dotfiles
SOURCE="${(%):-%N}"
while [[ -h "$SOURCE" ]]; do
    DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
export ZSHDIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
export DOTFILES="$(cd $ZSHDIR/.. && pwd)"

# Disable global zsh configuration on OSX, path_helper doesn't help with sane path sanitization, have to do this by ourselves
if [[ "$OSTYPE" == darwin* ]]; then
    unsetopt GLOBAL_RCS
fi

# We'll do this later in zshrc by ourselves
skip_global_compinit=1

for envfile in "$ZSHDIR"/env.d/*; do
    source $envfile
done

# Include local zshenv
if [[ -f "$ZSHDIR/zshenv.local" ]]; then
    source "$ZSHDIR/zshenv.local"
fi

# Include standard zshrc
if [[ -o interactive ]]; then
    source "$ZSHDIR/zshrc"
fi
