#!/usr/bin/env zsh

if (( ${+commands[delta]} )); then
    exec delta
elif (( ${+commands[diff-so-fancy]} )); then
    diff-so-fancy | less --quit-if-one-screen --pattern '^(Date|added|deleted|modified): '
else
    exec less --quit-if-one-screen
fi
